{% set name = "funcy" %}
{% set version = "2.1" %}
{% set sha256 = "8979feb3de7120afd1d00e5a8eae810c1942e4bfbc91697151e9ee1e49f79284" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - funcy
  commands:
    - pip check

about:
  home: https://github.com/Suor/funcy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of fancy functional tools focused on practicality.

  doc_url: http://funcy.readthedocs.io/
  dev_url: https://github.com/Suor/funcy

extra:
  recipe-maintainers:
    - synapticarbors
