{% set name = "funcy" %}
{% set version = "1.15" %}
{% set sha256 = "65b746fed572b392d886810a98d56939c6e0d545abb750527a717c21ced21008" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - funcy

about:
  home: https://github.com/Suor/funcy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of fancy functional tools focused on practicality.

  doc_url: http://funcy.readthedocs.io/
  dev_url: https://github.com/Suor/funcy

extra:
  recipe-maintainers:
    - synapticarbors
