{% set name = "funcy" %}
{% set version = "1.10.2" %}
{% set sha256 = "95cbcd47b66e1fcc5737ef8f1f66be8626540ed181acaa8b483963d1af860510" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - funcy

about:
  home: https://github.com/Suor/funcy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A collection of fancy functional tools focused on practicality.'

  doc_url: http://funcy.readthedocs.io/
  dev_url: https://github.com/Suor/funcy

extra:
  recipe-maintainers:
    - synapticarbors
